const A=require('node:assert/strict'),{Store:S,Defaults,Utils:U,DateUtils:D,TaskService:T,TransferService:X,CalendarService:C,RecurrenceService:R,ReservationService:Res,FactService:F,AnalyticsService:N}=require('../app.js');
let count=0;function setup(){S.init({raw:null,getItem(){return this.raw},setItem(k,v){this.raw=v}});Res.ensure(S.state,U.monday());}function test(n,fn){setup();fn();count++;console.log('OK '+n)}
function b(extra={}){return{title:'Проверка',startDateTime:U.monday()+'T19:00',endDateTime:U.monday()+'T20:00',primaryAreaId:S.state.lifeAreas[1].id,additionalAreaIds:[],taskIds:[],protected:true,status:'planned',energyRequired:'medium',note:'',actualMinutes:null,...extra}}
test('Повреждённая дата отклоняется до импорта и при загрузке',()=>{const s=Defaults.state();s.tasks=[{...T.fresh(),areaId:s.lifeAreas[0].id,title:'Проверка',createdAt:{bad:true}}];const raw=JSON.stringify(s);A.throws(()=>X.parse(raw),/дата/);const mem={raw,getItem(){return this.raw},setItem(){throw Error('Не должно записываться')}};S.init(mem);A(S.blocked);A.equal(mem.raw,raw)});
test('Обязательные поля задач не допускают неверных типов',()=>{T.save({...T.fresh(),title:'Тест'});for(const [k,v]of[['createdAt',null],['notes',{}],['blockIds',[null]],['tags',{}],['importance','1']]){const s=U.clone(S.state);s.tasks[0][k]=v;A.throws(()=>X.parse(JSON.stringify(s)),k)}});
test('Таймер без длительностей не проходит восстановление',()=>{S.state.uiState.focusTimer={id:'bad',phase:'work',status:'paused',durationMs:60000,elapsedMs:0,segments:[]};A.throws(()=>X.parse(JSON.stringify(S.state)),/длительности/)});
test('Известный ноль рабочего факта проходит полный круг экспорта',()=>{const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'manual',r.startDateTime,r.startDateTime);const s=X.parse(S.snapshot());A.equal(s.reservationFacts[0].actualMinutes,0);X.replace(s);A.equal(S.state.reservationFacts[0].actualMinutes,0)});
test('Неверный импорт через replace оставляет данные неизменными',()=>{const old=S.snapshot(),s=JSON.parse(old);s.tasks=[{id:'bad'}];A.throws(()=>X.replace(s));A.equal(S.snapshot(),old)});
test('Семь нарушенных повторов считаются семью',()=>{C.commit(C.prepare({block:b(),recurrence:{frequency:'daily',weekdays:[]}}));const old=R.blocks(S.state,U.monday(),U.monday())[0];C.commit(C.prepare({old,remove:true,scope:'all',dueToWork:true}));const m=N.calculate(S.state,U.monday());A.equal(m.lost,420);A.equal(m.violatedCount,7)});
test('Рабочая строка помечает частичный физический факт',()=>{const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'planned_as_actual');const row=N.calculate(S.state,U.monday()).rows[0];A.equal(row.normFact,540);A.equal(row.normPartial,true)});
test('Максимум без минимума и комфорт не считаются отсутствующими',()=>{const a=S.state.lifeAreas[1];a.maximumHours=1;C.commit(C.prepare({block:b()}));A.equal(N.calculate(S.state,U.monday()).rows[1].status,'Максимум не превышен');S.state.lifeAreas[1].maximumHours=null;S.state.lifeAreas[1].comfortHours=2;A.equal(N.calculate(S.state,U.monday()).rows[1].status,'Задан ориентир комфорта')});
test('Ошибка синтаксиса и типов имеет русское сообщение',()=>{A.throws(()=>X.parse('{'),/Файл не является корректным JSON/);const s=Defaults.state();s.settings.work=null;A.throws(()=>X.parse(JSON.stringify(s)),/Повреждена структура/)});
test('Исправление старого снимка не переписывает физические числа',()=>{const week=D.add(U.monday(),-7);Res.ensure(S.state,week);N.snapshot(S.state,week);const snap=S.state.weekSnapshots[0];delete snap.metrics.modelVersion;snap.metrics.rows[0].normPartial=undefined;snap.metrics.physical=1234;const before=snap.sourceDataRevision;N.snapshot(S.state,week);A.equal(snap.metrics.physical,1234);A.equal(snap.metrics.modelVersion,2);A.equal(snap.sourceDataRevision,before+1);N.snapshot(S.state,week);A.equal(snap.sourceDataRevision,before+1)});
console.log(`${count}/${count} passed`);
