const {chromium}=require('playwright'),A=require('node:assert/strict');const {Store:S,Defaults,Utils:U,DateUtils:D,CalendarService:C,ReservationService:R,AnalyticsService:N}=require('../app.js');
(async()=>{const browser=await chromium.launch({channel:process.argv[2]||'chrome',headless:true});try{const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await ctx.newPage(),errors=[];page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));const btn=n=>page.getByRole('button',{name:n,exact:true}),nav=n=>page.getByRole('navigation').getByRole('button',{name:n,exact:true}).click(),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('life168_app')));let count=0;async function test(n,fn){await fn();count++;console.log('OK '+n)}
await page.goto('http://127.0.0.1:4186');await btn('Пропустить').click();
await test('Новые значки, Венера, уменьшение движения и мобильная ширина',async()=>{await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('life168_app'));s.lifeAreas.find(a=>a.name==='Культура').icon='circle';localStorage.setItem('life168_app',JSON.stringify(s));});await page.reload();await nav('Сферы жизни');A(await page.locator('.area-illustration').count()>=13);A.equal(await page.locator('.icon-venus').count(),1);const card=page.locator('.area-card').filter({has:page.getByRole('heading',{name:'Культура',exact:true})});await card.hover();A.equal(await card.locator('svg').evaluate(n=>getComputedStyle(n).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});await card.hover();A.equal(await card.locator('svg').evaluate(n=>getComputedStyle(n).animationName),'area-greeting');await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:'tests/areas-refined-desktop.png',fullPage:true});for(const width of[390,320]){await page.setViewportSize({width,height:900});A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.setViewportSize({width:390,height:900});await card.scrollIntoViewIfNeeded();await page.screenshot({path:'tests/areas-refined-mobile.png'});await page.setViewportSize({width:1440,height:1000});await card.getByRole('button',{name:'Изменить',exact:true}).click();A.equal(await page.getByLabel('Значок',{exact:true}).inputValue(),'venus');await page.getByLabel('Значок',{exact:true}).selectOption('heart');await btn('Сохранить').click();await page.reload();A.equal((await state()).lifeAreas.find(a=>a.name==='Культура').icon,'heart');});
S.init({getItem(){return null},setItem(){}});const past=D.add(U.monday(),-7);S.state.settings.effectiveFrom=D.add(past,-14);S.state.uiState.onboardingComplete=true;S.state.uiState.selectedDate=past;R.ensure(S.state,past);const area=S.state.lifeAreas[1].id;
const make=(id,start,end)=>({id,title:id,startDateTime:past+'T'+start,endDateTime:past+'T'+end,plannedMinutes:60,primaryAreaId:area,additionalAreaIds:[],taskIds:[],protected:true,status:'planned',energyRequired:'medium',note:'',actualMinutes:null});
C.commit(C.prepare({block:make('Потеря','19:00','20:00')}));const old=S.state.calendarBlocks[0];C.commit(C.prepare({old,remove:true,dueToWork:true}));C.commit(C.prepare({block:make('Восстановление','20:00','21:00')}));N.snapshot(S.state,past);
await page.evaluate(s=>localStorage.setItem('life168_app',JSON.stringify(s)),S.state);await page.reload();
await test('Исторический факт: отмена не меняет данные, подтверждение пересчитывает снимок',async()=>{const before=await state(),snap=before.weekSnapshots.find(x=>x.weekId===D.weekId(past));await page.getByRole('button',{name:/^Рабочий день 09:00/}).last().click();await btn('По плану').click();await page.getByRole('heading',{name:'Изменить завершённую неделю?',exact:true}).waitFor();A.deepEqual((await state()).reservationFacts,before.reservationFacts);await btn('Отмена').click();await btn('По плану').click();await btn('Подтвердить пересчёт').click();const after=await state();A.equal(after.reservationFacts[0].actualMinutes,540);A.equal(after.weekSnapshots.find(x=>x.weekId===snap.weekId).sourceDataRevision,snap.sourceDataRevision+1);});
await test('Историческая компенсация требует подтверждения',async()=>{const before=await state();await btn('Учесть восстановление').click();await page.getByLabel('Восстановлено минут',{exact:true}).fill('30');await btn('Сохранить восстановление').click();await page.getByRole('heading',{name:'Изменить завершённую неделю?',exact:true}).waitFor();A.deepEqual((await state()).displacementLog,before.displacementLog);await btn('Подтвердить пересчёт').click();A.equal((await state()).displacementLog[0].resolvedMinutes,30);});
await test('Повреждённый импорт не заменяет состояние; сообщение по-русски',async()=>{await nav('Настройки');const before=await state();const upload=raw=>page.getByLabel('Импортировать JSON',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(raw)});await upload('{');await page.getByText(/Файл не является корректным JSON/).waitFor();A.deepEqual(await state(),before);const bad=structuredClone(before);bad.settings.focus={workMinutes:50};await upload(JSON.stringify(bad));await page.getByText(/Проверь длительности таймера/).waitFor();A.deepEqual(await state(),before);});
await test('Сумма четырёх недель сохраняет отметку неполного факта',async()=>{const s=Defaults.state();s.settings.effectiveFrom=D.add(U.monday(),-21);s.uiState.onboardingComplete=true;s.uiState.activeSection='analytics';s.uiState.analyticsPeriod='four';s.calendarBlocks=[null,60].map((actualMinutes,i)=>({id:'partial-'+i,title:'Здоровье',startDateTime:D.add(U.monday(),i===0?-7:0)+'T19:00',endDateTime:D.add(U.monday(),i===0?-7:0)+'T20:00',plannedMinutes:60,primaryAreaId:s.lifeAreas[1].id,additionalAreaIds:[],taskIds:[],protected:false,status:'planned',energyRequired:'medium',note:'',actualMinutes}));await page.evaluate(s=>localStorage.setItem('life168_app',JSON.stringify(s)),s);await page.reload();const row=page.locator('.analytics-chart').nth(2).locator('.chart-row').filter({hasText:'Здоровье и тело'});A((await row.innerText()).includes('частично'));});
A.deepEqual(errors,[]);console.log(JSON.stringify({passed:count,errors}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
