const {chromium}=require('playwright'),A=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:process.argv[2]||'chrome',headless:true});try{const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const btn=n=>page.getByRole('button',{name:n,exact:true}),nav=n=>page.getByRole('navigation').getByRole('button',{name:n,exact:true}).click(),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('life168_app')));let count=0;async function test(n,f){await f();count++;console.log('OK '+n)}
await page.goto('http://127.0.0.1:4186');await btn('Пропустить').click();
await test('Аналитика: шесть графиков, все показатели, три периода и reload',async()=>{await nav('Аналитика');A.equal(await page.locator('.analytics-chart').count(),6);await page.getByText('Показать все показатели',{exact:true}).click();A(await page.getByText('Спрос на ёмкость',{exact:true}).isVisible());await page.getByLabel('Период аналитики',{exact:true}).selectOption('four');A.equal(await page.locator('.analytics-key').count(),8);await page.reload();A.equal(await page.getByLabel('Период аналитики',{exact:true}).inputValue(),'four');await page.getByLabel('Период аналитики',{exact:true}).selectOption('previous');await page.getByLabel('Период аналитики',{exact:true}).selectOption('current');});
await test('Мобильные размеры, порядок карточек, раскрытие и высота графиков',async()=>{for(const width of[1440,1024,768,390,320]){await page.setViewportSize({width,height:1000});A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const sizes=await page.locator('.chart-content').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().height));A(sizes.every(h=>h>=239.99),JSON.stringify({width,sizes}));if(width===390)await page.screenshot({path:'tests/step5-mobile.png',fullPage:true});}const labels=await page.locator('.analytics-key').first().locator('.metric-card>span').allTextContents();A.deepEqual(labels,['Статус загрузки','Свободный резерв','Поглощение личного времени','Жизнь вне работы']);await page.locator('.analytics-chart summary').first().focus();await page.keyboard.press('Enter');A.equal(await page.locator('.analytics-chart').first().getAttribute('open'),null);await page.keyboard.press('Enter');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'tests/step5-desktop.png',fullPage:true});});
let exported;
await test('JSON и две CSV выгрузки скачиваются',async()=>{await nav('Настройки');for(const name of['Скачать резервную копию','CSV задач','CSV недельной аналитики']){const download=page.waitForEvent('download');await btn(name).first().click();const d=await download;A(d.suggestedFilename().startsWith('life168-'));const raw=fs.readFileSync(await d.path(),'utf8');if(name==='Скачать резервную копию'){exported=raw;A(JSON.parse(raw).dataVersion===1);A(d.suggestedFilename().includes('резервная копия'));}else A(raw.includes(';'));}});
async function upload(raw){await page.getByLabel('Импортировать JSON',{exact:true}).setInputFiles({name:'copy.json',mimeType:'application/json',buffer:Buffer.from(raw)});}
await test('Ошибка JSON и недопустимый статус не меняют данные',async()=>{const before=await state();await upload('{');await page.getByText(/Импорт не выполнен:/).waitFor();A.deepEqual(await state(),before);const bad=JSON.parse(exported);bad.dataVersion=99;await upload(JSON.stringify(bad));A.deepEqual(await state(),before);});
await test('Сводка и отмена импорта сохраняют текущее состояние',async()=>{const before=await state();await upload(exported);await page.getByRole('dialog').waitFor();A(await page.getByRole('dialog').getByText(/Сферы:/).isVisible());await btn('Отмена').click();A.deepEqual(await state(),before);});
await test('Импорт подтверждается, HTML остаётся текстом, данные переживают reload',async()=>{const s=JSON.parse(exported);s.profile.name='<img src=x onerror=alert(1)>';await upload(JSON.stringify(s));await btn('Заменить данные').click();A.equal((await state()).profile.name,s.profile.name);A.equal(await page.locator('img').count(),0);await page.reload();A.equal((await state()).profile.name,s.profile.name);});
await test('Офлайн аналитика и её сохранённый период',async()=>{await ctx.setOffline(true);await nav('Аналитика');await page.getByLabel('Период аналитики',{exact:true}).selectOption('four');A.equal(await page.locator('.analytics-chart').count(),6);await ctx.setOffline(false);});
await test('Полный сброс требует слово, отменяется и открывает знакомство',async()=>{await nav('Настройки');await btn('Удалить все данные').click();await page.getByLabel('Введи УДАЛИТЬ для подтверждения',{exact:true}).fill('нет');await btn('Удалить данные').click();A(await page.getByRole('dialog').isVisible());await btn('Отмена').click();A.equal((await state()).profile.name,'<img src=x onerror=alert(1)>');await btn('Удалить все данные').click();await page.getByLabel('Введи УДАЛИТЬ для подтверждения',{exact:true}).fill('УДАЛИТЬ');await btn('Удалить данные').click();await btn('Пропустить').waitFor();A.equal((await state()).tasks.length,0);});
await test('Три файла открываются напрямую без сервера, данные сохраняются',async()=>{await page.goto(require('node:url').pathToFileURL(require('node:path').resolve('index.html')).href);await btn('Пропустить').click();await nav('Аналитика');A.equal(await page.locator('.analytics-chart').count(),6);await page.reload();A.equal(await page.locator('.analytics-chart').count(),6);A.equal((await state()).uiState.activeSection,'analytics');});
A.deepEqual(errors,[]);console.log(JSON.stringify({passed:count,errors}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
