const {chromium}=require('playwright'), A=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:process.argv[2]||'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],results=[];
 page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const btn=n=>page.getByRole('button',{name:n,exact:true}),nav=n=>page.getByRole('navigation').getByRole('button',{name:n,exact:true}).click(),st=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('life168_app'))),step=async(n,f)=>{await f();results.push(n);console.log('OK '+n)},label=n=>page.getByLabel(n,{exact:true});
 const confirm=async()=>{if(await btn('Сохранить с подтверждением').isVisible())await btn('Сохранить с подтверждением').click();};
 await page.goto('http://127.0.0.1:4186');await btn('Пропустить').click();
 const date=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});
 await step('Создание задачи, черновик после reload, все поля и безопасный текст',async()=>{
  await nav('Задачи');await btn('+ Добавить задачу').click();await label('Название задачи').fill('Презентация');await label('Заметки задачи').fill('Архитектура <img src=x onerror=alert(1)>');await label('Минимальная версия').fill('Структура из 10 слайдов');await label('Теги через запятую').fill('проект, дизайн');await label('Рычаг').fill('5');await label('Оценка, минут').fill('90');await label('Дедлайн задачи').fill(date);await page.keyboard.press('Escape');await page.reload();await btn('Продолжить черновик').click();A.equal(await label('Название задачи').inputValue(),'Презентация');await btn('Сохранить задачу').click();const t=(await st()).tasks[0];A.equal(t.actualMinutes,null);A.equal(t.estimatedMinutes,90);A.equal(t.leverage,5);A.equal(t.minimumVersion,'Структура из 10 слайдов');await btn('Открыть задачу').click();A.equal(await page.locator('dialog img').count(),0);await btn('Закрыть').click();
 });
 await step('Планирование двух блоков и автоматический статус задачи',async()=>{
  for(const [start,end]of [['19:00','20:00'],['20:00','20:30']]){await btn('Запланировать').click();await label('Дата и время начала').fill(date+'T'+start);await label('Дата и время окончания').fill(date+'T'+end);await btn('Сохранить блок').click();await confirm();}
  A.equal((await st()).tasks[0].blockIds.length,2);A.equal((await st()).tasks[0].status,'planned');await page.reload();A.equal((await st()).tasks[0].blockIds.length,2);
 });
 await step('Выполнено по плану, ручной факт, ноль и отсутствие факта',async()=>{
  await btn('Открыть задачу').click();await page.getByRole('dialog').getByRole('button').filter({hasText:'19:00 · Презентация'}).click();await btn('Выполнено по плану').click();await confirm();let s=await st();A.equal(s.calendarBlocks.find(b=>b.startDateTime.endsWith('T19:00')).actualMinutes,60);A.equal(s.tasks[0].status,'planned');
  for(const [value,expected]of [['45',45],['0',0],['',null]]){await btn('Открыть задачу').click();await page.getByRole('dialog').getByRole('button').filter({hasText:'19:00 · Презентация'}).click();await btn('Внести факт').click();await label('Факт блока, минут').fill(value);await btn('Сохранить факт').click();await confirm();A.equal((await st()).calendarBlocks.find(b=>b.startDateTime.endsWith('T19:00')).actualMinutes,expected);}
 });
 await step('Ручной факт задачи заменяется и статусы доступны',async()=>{
  await btn('Открыть задачу').click();await btn('Редактировать задачу').click();await label('Факт задачи, минут').fill('75');await btn('Сохранить задачу').click();A.equal((await st()).tasks[0].actualMinutes,75);A.equal((await st()).tasks[0].actualMinutesManualOverride,true);
  for(const [name,status]of [['Начать','in_progress'],['Отложить','postponed'],['Отменить задачу','cancelled'],['Вернуть во входящие','inbox'],['Завершить задачу','completed']]){if(!await page.locator('dialog').isVisible())await btn('Открыть задачу').click();await page.getByRole('dialog').getByRole('button',{name,exact:true}).click();A.equal((await st()).tasks[0].status,status);}await btn('Закрыть').click();
 });
 await step('Связи с блоками можно снять, завершённый статус сохраняется',async()=>{await btn('Открыть задачу').click();await btn('Связать с блоками').click();for(const checkbox of await page.locator('dialog input[type=checkbox]').all())await checkbox.uncheck();await btn('Сохранить связи').click();A.equal((await st()).tasks[0].blockIds.length,0);A.equal((await st()).tasks[0].status,'completed');await btn('Закрыть').click();});
 await step('Поиск заметок, фильтры, сортировка и восстановление фильтров',async()=>{await label('Поиск по тексту и заметкам').fill('АРХИТЕКТУРА');await label('Выполнение').selectOption('yes');await label('Порядок').selectOption('leverage');await btn('Применить фильтры').click();A.equal(await page.locator('[data-task-id]').count(),1);await page.reload();A.equal(await label('Поиск по тексту и заметкам').inputValue(),'АРХИТЕКТУРА');await label('Выполнение').selectOption('no');await btn('Применить фильтры').click();A.equal(await page.locator('[data-task-id]').count(),0);await btn('Сбросить фильтры').click();});
 await step('Входящие: несколько строк, черновик, категории и архив',async()=>{
  await nav('Входящие');await btn('+ Добавить запись').click();await label('Мысли и дела').fill('Купить книгу\n\nПрогулка в парке');await page.keyboard.press('Escape');await page.reload();await btn('Продолжить черновик').click();A((await label('Мысли и дела').inputValue()).includes('Прогулка'));await btn('Добавить во входящие').click();A.equal((await st()).brainDumpItems.length,2);
  const card=page.locator('article').filter({hasText:'Купить книгу'});await card.getByRole('button',{name:'Разобрать запись'}).click();await label('Категория записи').selectOption('task');await label('Текст записи').fill('Купить книгу по дизайну');await page.keyboard.press('Escape');await page.reload();await btn('Продолжить разбор').click();A.equal(await label('Текст записи').inputValue(),'Купить книгу по дизайну');await btn('Сохранить запись').click();
  await page.locator('article').filter({hasText:'Прогулка'}).getByRole('button',{name:'Отметить разобранной'}).click();A.equal(await page.locator('[data-inbox-id]').count(),1);await label('Разбор').selectOption('yes');await btn('Применить фильтры').click();A.equal(await page.locator('[data-inbox-id]').count(),1);await btn('Вернуть из архива').click();await btn('Сбросить фильтры').click();
 });
 await step('Преобразование в задачу: отмена не разбирает запись, сохранение без дубликатов',async()=>{
  await page.locator('article').filter({hasText:'Купить книгу'}).getByRole('button',{name:'Разобрать запись'}).click();await btn('Преобразовать в задачу').click();await btn('Отмена').click();A.equal((await st()).brainDumpItems.find(i=>i.text.includes('Купить')).processed,false);
  await page.locator('article').filter({hasText:'Купить книгу'}).getByRole('button',{name:'Разобрать запись'}).click();await btn('Преобразовать в задачу').click();await btn('Сохранить задачу').click();A.equal((await st()).tasks.length,2);A((await st()).brainDumpItems.find(i=>i.text.includes('Купить')).processed);await label('Разбор').selectOption('yes');await btn('Применить фильтры').click();await btn('Разобрать запись').click();await btn('Открыть созданную задачу').click();A.equal((await st()).tasks.length,2);await btn('Закрыть').click();await btn('Сбросить фильтры').click();
 });
 await step('Преобразование входящей записи в блок и сохранение заметки',async()=>{await btn('Разобрать запись').click();await btn('Преобразовать в блок').click();await label('Дата и время начала').fill(date+'T21:00');await label('Дата и время окончания').fill(date+'T21:30');await btn('Сохранить блок').click();await confirm();A((await st()).brainDumpItems.find(i=>i.text.includes('Прогулка')).convertedBlockId);A((await st()).calendarBlocks.some(b=>b.note==='Прогулка в парке'));});
 await step('Глобальный поиск находит задачу, входящую и заметки блока',async()=>{await btn('Поиск по всем разделам').click();await label('Искать во всех разделах').fill('Прогулка');await btn('Найти').click();A.equal(await page.locator('dialog .work-list button').count(),2);await page.keyboard.press('Escape');});
 await step('Подтверждение работы и дороги: по плану, вручную, неизвестно',async()=>{
  await nav('Настройки');await label('Учитывать дорогу на работу').check();await btn('Сохранить настройки').click();await nav('Моя неделя');await label('Выбрать дату и неделю').fill(date);await label('Выбрать дату и неделю').dispatchEvent('change');
  const work=()=>page.locator('.daily-facts').getByRole('button').filter({hasText:'Рабочий день'});await work().click();await btn('По плану').click();A.equal((await st()).reservationFacts.find(f=>f.type==='work').actualMinutes,540);
  await work().click();await label('Фактическое начало').fill(date+'T10:00');await label('Фактическое окончание').fill(date+'T17:00');await btn('Изменить').click();A.equal((await st()).reservationFacts.find(f=>f.type==='work').actualMinutes,420);
  await page.locator('.daily-facts').getByRole('button').filter({hasText:'Дорога'}).first().click();await btn('По плану').click();A.equal((await st()).reservationFacts.find(f=>f.type==='commute').actualMinutes,60);await work().click();await btn('Не фиксировать').click();A(!(await st()).reservationFacts.some(f=>f.type==='work'));
  await nav('168 часов');A((await page.locator('.daily-facts').innerText()).includes('недостаточно данных'));
 });
 await step('Удаление задачи и записи требует подтверждения',async()=>{await nav('Задачи');await page.locator('article').filter({hasText:'Купить книгу'}).getByRole('button',{name:'Открыть задачу'}).click();await btn('Удалить задачу').click();await btn('Отмена').click();A.equal((await st()).tasks.length,2);await btn('Удалить задачу').click();await btn('Удалить').click();A.equal((await st()).tasks.length,1);await nav('Входящие');await label('Разбор').selectOption('yes');await btn('Применить фильтры').click();await page.locator('article').filter({hasText:'Купить книгу'}).getByRole('button',{name:'Разобрать запись'}).click();await btn('Удалить запись').click();await btn('Удалить').click();A.equal((await st()).brainDumpItems.length,1);});
 await step('Адаптивность, скриншоты и клавиатура',async()=>{await page.waitForFunction(()=>!document.querySelector('.toast'));for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:1000});for(const section of ['Задачи','Входящие','168 часов']){await nav(section);if(width<768&&section!=='168 часов')A.equal(await page.locator('.filters-panel').getAttribute('open'),null);A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),section+' '+width);if([1440,390].includes(width)){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(__dirname,`step3-${width}-${section==='Задачи'?'tasks':section==='Входящие'?'inbox':'budget'}.png`),animations:'disabled'});}}}await nav('Задачи');await btn('+ Добавить задачу').focus();await page.keyboard.press('Enter');A(await page.locator('dialog').isVisible());A(await page.locator('dialog').evaluate(e=>e.getBoundingClientRect().width)<=320);await page.keyboard.press('Tab');A(await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));await page.keyboard.press('Escape');});
 A.deepEqual(errors,[]);console.log(JSON.stringify({passed:results.length,results,errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
