const A=require('node:assert/strict');
const {Defaults:D,Store:S,Utils:U,TaskService:T,InboxService:N,FactService:F,SearchService:Q,CalendarService:C,RecurrenceService:R,ReservationService:V,BudgetService:B,DateUtils:X}=require('../app.js');
const tests=[],test=(n,f)=>tests.push([n,f]),week=U.monday(),day=n=>X.add(week,n);
function setup(){const mem={raw:null,getItem(){return this.raw},setItem(k,v){this.raw=v}};S.init(mem);return mem;}
function task(extra={}){const t={...T.fresh(),title:'Проект',...extra};T.save(t);return S.state.tasks.find(x=>x.id===t.id);}
function block(extra={}){return {id:U.id(),title:'Работа над проектом',startDateTime:week+'T19:00',endDateTime:week+'T20:00',primaryAreaId:S.state.lifeAreas[2].id,additionalAreaIds:[],protected:false,status:'planned',energyRequired:'medium',actualMinutes:null,note:'',taskIds:[],...extra};}
function add(b,more={}){const p=C.prepare({block:b,...more});C.commit(p);return S.state.calendarBlocks.find(x=>x.id===p.block.id);}
test('Новая задача: необязательные значения null и статус inbox',()=>{setup();const t=task();A.equal(t.actualMinutes,null);A.equal(t.estimatedMinutes,null);A.equal(t.deadline,null);A.equal(t.status,'inbox');});
test('Валидация задачи: лимиты, шкалы, теги, дата, оценка и факт',()=>{setup();const t=task();for(const change of [{title:''},{title:'x'.repeat(121)},{notes:'x'.repeat(2001)},{minimumVersion:'x'.repeat(501)},{leverage:6},{importance:0},{urgency:1.5},{estimatedMinutes:0},{estimatedMinutes:1.5},{actualMinutes:-1},{actualMinutes:1.5},{deadline:'2026-02-30'},{tags:Array(11).fill('a')},{tags:['a'.repeat(31)]},{status:'bad'}])A.throws(()=>T.save({...t,...change}));T.save({...t,actualMinutes:0,estimatedMinutes:1,notes:'a'.repeat(2000),minimumVersion:'b'.repeat(500)});});
test('Все статусы вручную и completedAt',()=>{setup();const t=task();for(const status of ['planned','in_progress','completed','postponed','cancelled','inbox']){T.status(t.id,status);const saved=S.state.tasks[0];A.equal(saved.status,status);A.equal(Boolean(saved.completedAt),status==='completed');}});
test('Первый блок планирует задачу; два блока не удваивают бюджет',()=>{setup();const t=task({estimatedMinutes:900,actualMinutes:700});const a=add(block({taskIds:[t.id]}));add(block({taskIds:[t.id],startDateTime:week+'T20:00',endDateTime:week+'T21:00'}));A.equal(S.state.tasks[0].status,'planned');A.equal(S.state.tasks[0].blockIds.length,2);A.equal(B.calculate(S.state,week).physical,6180);A(S.state.tasks[0].blockIds.includes(a.id));});
test('Завершение блока не завершает задачу; отмена последнего возвращает inbox',()=>{setup();const t=task();let b=add(block({taskIds:[t.id]}));let p=C.prepare({old:b,block:{...b,status:'completed',actualMinutes:60}});C.commit(p);A.equal(S.state.tasks[0].status,'planned');b=S.state.calendarBlocks[0];p=C.prepare({old:b,block:{...b,status:'cancelled'}});C.commit(p);A.equal(S.state.tasks[0].status,'inbox');A.deepEqual(S.state.tasks[0].blockIds,[]);});
test('Удаление блоков сохраняет ручные статусы',()=>{for(const status of ['in_progress','completed','postponed','cancelled']){setup();const t=task();const b=add(block({taskIds:[t.id]}));T.status(t.id,status);C.commit(C.prepare({old:b,remove:true}));A.equal(S.state.tasks[0].status,status);}});
test('Перенос и копирование поддерживают связи',()=>{setup();const t=task();let b=add(block({taskIds:[t.id]}));C.commit(C.prepare({old:b,block:{...b,startDateTime:day(2)+'T19:00',endDateTime:day(2)+'T20:00'}}));A.equal(S.state.tasks[0].blockIds[0],b.id);add({...b});A.equal(S.state.tasks[0].blockIds.length,2);});
test('Связь с виртуальным повтором материализует один экземпляр',()=>{setup();const t=task();C.commit(C.prepare({block:block(),recurrence:{frequency:'daily',weekdays:[]}}));const b=R.blocks(S.state,week,day(6))[1];T.links(t.id,[b]);A.equal(S.state.calendarBlocks.length,1);A.equal(S.state.tasks[0].blockIds.length,1);A.equal(R.blocks(S.state,week,day(6)).length,7);});
test('Создание серии из задачи связывает только первый экземпляр',()=>{setup();const t=task();add(block({taskIds:[t.id]}),{recurrence:{frequency:'daily',weekdays:[]}});A.equal(S.state.tasks[0].blockIds.length,1);A.equal(S.state.recurrenceSeries[0].template.taskIds.length,0);A.equal(R.blocks(S.state,week,day(6)).length,7);});
test('Удаление всей серии убирает ссылки задачи',()=>{setup();const t=task();add(block({taskIds:[t.id]}),{recurrence:{frequency:'daily',weekdays:[]}});const b=S.state.calendarBlocks[0];C.commit(C.prepare({old:b,remove:true,scope:'all'}));A.equal(S.state.tasks[0].blockIds.length,0);A.equal(S.state.tasks[0].status,'inbox');});
test('Удаление задачи оставляет блок и освобождает связь',()=>{setup();const t=task();add(block({taskIds:[t.id]}));T.remove(t.id);A.equal(S.state.calendarBlocks.length,1);A.deepEqual(S.state.calendarBlocks[0].taskIds,[]);});
test('Входящие: строки, категории, архив и ограничения',()=>{setup();N.add('  Мысль\n\nИдея  ',true,'idea');A.equal(S.state.brainDumpItems.length,2);const i=S.state.brainDumpItems[0];N.update(i.id,{category:'worry',processed:true});A.equal(i.category,'worry');A(i.processed);A.throws(()=>N.add('x'.repeat(2001),false,'thought'));A.throws(()=>N.add(' ',true,'thought'));N.remove(i.id);A.equal(S.state.brainDumpItems.length,1);});
test('Конвертация в задачу атомарна и не дублируется',()=>{setup();N.add('Мысль',false,'thought');const i=S.state.brainDumpItems[0];A.throws(()=>T.save({...T.fresh(),title:''},i.id));A.equal(i.processed,false);const t={...T.fresh(),title:'Мысль'};T.save(t,i.id);A.equal(i.convertedTaskId,t.id);A(i.processed);A.throws(()=>T.save({...T.fresh(),title:'Копия'},i.id));});
test('Конвертация в блок только после commit; копий нет',()=>{setup();N.add('Событие',false,'event');const i=S.state.brainDumpItems[0],p=C.prepare({block:block({sourceInboxId:i.id})});A.equal(S.state.brainDumpItems[0].processed,false);C.commit(p);A.equal(S.state.brainDumpItems[0].convertedBlockId,p.block.id);A.throws(()=>C.prepare({block:block({sourceInboxId:i.id})}));});
test('Ручной факт заменяет значение, не меняя план',()=>{setup();let b=add(block());A.equal(b.actualMinutes,null);C.commit(C.prepare({old:b,block:{...b,actualMinutes:60,status:'completed'}}));b=S.state.calendarBlocks[0];C.commit(C.prepare({old:b,block:{...b,actualMinutes:0}}));A.equal(S.state.calendarBlocks[0].plannedMinutes,60);A.equal(S.state.calendarBlocks[0].actualMinutes,0);C.commit(C.prepare({old:S.state.calendarBlocks[0],block:{...S.state.calendarBlocks[0],actualMinutes:null}}));A.equal(S.state.calendarBlocks[0].actualMinutes,null);for(const actualMinutes of [-1,1.5,1441])A.throws(()=>C.prepare({block:block({actualMinutes})}));});
test('Неизвестный факт и известный ноль различаются',()=>{setup();V.ensure(S.state,week);A.equal(F.calculate(S.state,week).work,null);add(block({primaryAreaId:S.state.lifeAreas[0].id,actualMinutes:0}));A.equal(F.calculate(S.state,week).work,0);});
test('Рабочий резерв по плану + детали внутри = 540, не 600',()=>{setup();V.ensure(S.state,week);const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'planned_as_actual');add(block({primaryAreaId:S.state.lifeAreas[0].id,startDateTime:week+'T10:00',endDateTime:week+'T11:00',actualMinutes:60}));A.equal(F.calculate(S.state,week).work,540);});
test('Без подтверждения резерва учитывается факт деталей',()=>{setup();V.ensure(S.state,week);add(block({primaryAreaId:S.state.lifeAreas[0].id,startDateTime:week+'T10:00',endDateTime:week+'T11:00',actualMinutes:45}));A.equal(F.calculate(S.state,week).work,45);A(F.calculate(S.state,week).partial);});
test('Ручное изменение резерва, частичный выход блока и отказ фиксации',()=>{setup();V.ensure(S.state,week);const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'manual',week+'T09:00',week+'T17:00');add(block({primaryAreaId:S.state.lifeAreas[0].id,startDateTime:week+'T16:00',endDateTime:week+'T18:00',actualMinutes:120}));A.equal(F.calculate(S.state,week).work,540);F.reservation(r.id,null);A.equal(F.calculate(S.state,week).work,120);A.throws(()=>F.reservation(r.id,'manual',week+'T18:00',week+'T09:00'));});
test('Подтверждённая дорога и полнота данных',()=>{setup();S.state.settings.commute.enabled=true;V.ensure(S.state,week);for(const r of S.state.capacityReservations.filter(r=>r.type!=='sleep'))F.reservation(r.id,'planned_as_actual');const f=F.calculate(S.state,week);A.equal(f.commute,600);A.equal(f.work,2700);A.equal(f.partial,false);A.equal(f.factPercent,f.planPercent);});
test('Пересекающиеся подтверждённые резервы объединяются',()=>{setup();V.ensure(S.state,week);const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'planned_as_actual');S.state.reservationFacts.push({...S.state.reservationFacts[0],reservationId:'duplicate'});A.equal(F.calculate(S.state,week).work,540);});
test('Факт и подтверждения сохраняются при изменении графика',()=>{setup();V.ensure(S.state,week);const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'planned_as_actual');S.state.settings.scheduleVersions[0].work.start='11:00';V.ensure(S.state,week);A.equal(F.calculate(S.state,week).work,540);});
test('Факт ночного блока распределяется по плановым долям недель',()=>{setup();const b=add(block({startDateTime:day(6)+'T23:00',endDateTime:day(7)+'T01:00',actualMinutes:90}));A.equal(F.portion(b,X.bounds(week)),45);A.equal(F.portion(b,X.bounds(day(7))),45);});
test('Поиск текста заметок, тегов, минимальной версии и сочетания фильтров',()=>{setup();const t=task({notes:'Обсудить архитектуру',minimumVersion:'Один слайд',tags:['дизайн'],leverage:5,deadline:week});for(const query of ['АРХИТЕКТУРУ','слайд','дизайн'])A(Q.matches(t,'tasks',{query,area:t.areaId,status:'inbox',date:week,done:'no',energy:'medium'}));A.equal(Q.matches(t,'tasks',{done:'yes'}),false);A.equal(Q.matches(t,'tasks',{date:day(1)}),false);A(Q.matches({text:'идея',category:'idea',processed:true},'inbox',{archive:'yes',category:'idea'}));});
test('Перезагрузка сохраняет задачи, связи, входящие и факт',()=>{const mem=setup();N.add('Заметка',false,'thought');const t=task({actualMinutes:20,actualMinutesManualOverride:true});add(block({taskIds:[t.id],actualMinutes:25}));const before=JSON.stringify(S.state);S.init(mem);A.equal(JSON.stringify(S.state),before);});
test('Факт прежнего графика доступен для изменения и удаления',()=>{setup();V.ensure(S.state,week);const r=S.state.capacityReservations.find(r=>r.type==='work');F.reservation(r.id,'planned_as_actual');S.state.settings.scheduleVersions[0].work.start='11:00';V.ensure(S.state,week);A(F.dayReservations(S.state,week).some(x=>x.id===r.id&&x.savedFact));F.reservation(r.id,'manual',week+'T10:00',week+'T17:00');A.equal(F.calculate(S.state,week).work,420);F.reservation(r.id,null);A.equal(F.calculate(S.state,week).work,null);});
test('Текущий факт не меняет снимок другой недели',()=>{setup();V.ensure(S.state,week);S.state.weekSnapshots=[{weekId:X.weekId(day(-7))},{weekId:X.weekId(week)}];F.reservation(S.state.capacityReservations.find(r=>r.type==='work').id,'planned_as_actual');A.equal(S.state.weekSnapshots[0].needsRecalculation,undefined);A.equal(S.state.weekSnapshots[1].needsRecalculation,true);});
test('Неизвестные детали не делают полный факт рабочего резерва частичным',()=>{setup();V.ensure(S.state,week);for(const r of S.state.capacityReservations.filter(r=>r.type==='work'))F.reservation(r.id,'planned_as_actual');add(block({primaryAreaId:S.state.lifeAreas[0].id,startDateTime:week+'T10:00',endDateTime:week+'T11:00'}));A.equal(F.calculate(S.state,week).partial,false);});
let failed=0;for(const[n,f]of tests)try{f();console.log('OK '+n)}catch(e){failed++;console.error('FAIL '+n+'\n'+e.stack)}console.log(`${tests.length-failed}/${tests.length} passed`);process.exitCode=failed?1:0;
