const A=require('node:assert/strict');
const {Store:S,Utils:U,Defaults,DateUtils:D,CalendarService:C,ReservationService:R,AnalyticsService:N,TransferService:T,TaskService:Tasks,SettingsService,FocusService:F}=require('../app.js');
let count=0;function test(name,fn){setup();fn();count++;console.log('OK '+name)}
function setup(){S.init({raw:null,getItem(){return this.raw},setItem(k,v){this.raw=v}});R.ensure(S.state,U.monday());S.revision++;S.save();}
function block(extra={}){const day=U.monday();const p=C.prepare({block:{title:'Личное',startDateTime:day+'T19:00',endDateTime:day+'T20:00',primaryAreaId:S.state.lifeAreas[1].id,additionalAreaIds:[],taskIds:[],status:'planned',energyRequired:'medium',protected:false,note:'',actualMinutes:null,...extra}});C.commit(p);return S.state.calendarBlocks.at(-1);}
test('Все физические минуты классифицированы ровно один раз',()=>{block();const m=N.calculate(S.state,U.monday());A.equal(Object.values(m.distribution).reduce((a,b)=>a+b,0),m.physical);A.equal(m.physical+m.free,10080);});
test('Сон имеет приоритет над работой и пользовательской сферой',()=>{block({startDateTime:U.monday()+'T23:00',endDateTime:D.add(U.monday(),1)+'T00:00'});const m=N.calculate(S.state,U.monday());A.equal(m.distribution.sleep,3360);A.equal(m.distribution[S.state.lifeAreas[1].id],undefined);A.equal(m.conflict,60);});
test('Рабочая детализация не добавляет долю в круг',()=>{const before=N.calculate(S.state,U.monday());block({startDateTime:U.monday()+'T10:00',endDateTime:U.monday()+'T11:00',primaryAreaId:S.state.lifeAreas[0].id});const m=N.calculate(S.state,U.monday());A.deepEqual(m.distribution,before.distribution);A.equal(m.rows[0].primaryPlan,60);A.equal(m.rows[0].normPlan,2700);});
test('Дополнительная сфера получает вклад, но не физическую долю',()=>{block({additionalAreaIds:[S.state.lifeAreas[2].id]});const m=N.calculate(S.state,U.monday());A.equal(m.rows[1].plan,60);A.equal(m.rows[2].plan,60);A.equal(m.rows[2].primaryPlan,0);A.equal(m.distribution[m.rows[2].id],undefined);});
test('Нулевой факт отличается от неизвестного',()=>{block({actualMinutes:0});const m=N.calculate(S.state,U.monday());A.equal(m.rows[1].fact,0);A.equal(m.rows[2].fact,null);A.equal(m.lifeFact,null);A.equal(m.absorption,null);});
test('Пропущенный план остаётся в истории без занятия ёмкости',()=>{block({status:'skipped'});const m=N.calculate(S.state,U.monday());A.equal(m.rows[1].plan,60);A.equal(m.distribution[m.rows[1].id],undefined);});
test('Нормативы и правило повторного недобора',()=>{S.state.lifeAreas[1].minimumHours=2;block();const m=N.calculate(S.state,U.monday());A.equal(m.rows[1].status,'Ниже минимума');A(N.insights(m,m).some(x=>x.includes('вторую неделю')));});
test('Снимок идемпотентен, настройки не переписывают прошлое',()=>{const day=D.add(U.monday(),-7);block({startDateTime:day+'T19:00',endDateTime:day+'T20:00'});const m=N.snapshot(S.state,day),raw=JSON.stringify(S.state.weekSnapshots);N.snapshot(S.state,day);A.equal(JSON.stringify(S.state.weekSnapshots),raw);S.state.settings.weeklyBufferPercent=49;S.state.lifeAreas[1].minimumHours=10;A.deepEqual(N.snapshot(S.state,day),m);});
test('Подтверждённая правка обновляет единственный снимок и ревизию',()=>{const day=D.add(U.monday(),-7),b=block({startDateTime:day+'T19:00',endDateTime:day+'T20:00'});N.snapshot(S.state,day);C.commit(C.prepare({old:b,block:{...b,actualMinutes:25}}));N.snapshot(S.state,day);A.equal(S.state.weekSnapshots.length,1);A.equal(S.state.weekSnapshots[0].sourceDataRevision,2);A.equal(S.state.weekSnapshots[0].metrics.rows[1].fact,25);});
test('Полный JSON проходит импорт без изменения данных',()=>{block();const task={...Tasks.fresh(),title:'<img src=x onerror=alert(1)>'};Tasks.save(task);N.sync(S.state);const before=JSON.parse(S.snapshot());A.deepEqual(T.parse(JSON.stringify(before)),before);});
test('Ошибки версии, структуры, перечислений и лимитов отвергаются',()=>{const base=S.snapshot();for(const mutate of[s=>s.dataVersion=99,s=>s.tasks={},s=>s.lifeAreas[0].name='x'.repeat(61)]){const s=JSON.parse(base);mutate(s);A.throws(()=>T.parse(JSON.stringify(s)));}block();for(const mutate of[s=>s.calendarBlocks[0].status='evil',s=>s.calendarBlocks[0].title='x'.repeat(121),s=>s.calendarBlocks[0].primaryAreaId='missing']){const s=JSON.parse(S.snapshot());mutate(s);A.throws(()=>T.parse(JSON.stringify(s)));}A.throws(()=>T.parse('{'));});
test('Квота импорта сохраняет старое состояние и хранилище',()=>{const before=S.snapshot();S.storage.setItem=()=>{throw Object.assign(Error('quota'),{name:'QuotaExceededError'})};A.throws(()=>T.replace(Defaults.state()));A.equal(S.snapshot(),before);A.equal(S.storage.raw,JSON.stringify(S.state));});
test('CSV экранирует разделители, кавычки и формулы',()=>{const csv=T.csv([['=1+1','a;"b','строка\nдва',null]]);A(csv.startsWith('\uFEFF'));A(csv.includes('"\'=1+1"'));A(csv.includes('"a;""b"'));});
test('1000 задач, 1500 блоков и 12 месяцев истории',()=>{const day=D.add(U.monday(),-364);S.state.settings.effectiveFrom=day;S.state.settings.scheduleVersions[0].effectiveFrom=day;const sample=block();S.state.calendarBlocks=Array.from({length:1500},(_,i)=>({...sample,id:'block-'+i,startDateTime:D.add(day,i%364)+'T19:00',endDateTime:D.add(day,i%364)+'T20:00'}));S.state.tasks=Array.from({length:1000},(_,i)=>({...Tasks.fresh(),title:'Задача '+i}));const start=performance.now();N.sync(S.state);const raw=S.snapshot();T.parse(raw);console.log(JSON.stringify({historyWeeks:S.state.weekSnapshots.length,bytes:Buffer.byteLength(raw),elapsedMs:Math.round(performance.now()-start)}));A.equal(S.state.tasks.length,1000);A.equal(S.state.calendarBlocks.length,1500);A(S.state.weekSnapshots.length>=52);});
test('Изменение ночного блока пересчитывает обе завершённые недели',()=>{const day=D.add(U.monday(),-8),b=block({startDateTime:day+'T23:00',endDateTime:D.add(day,1)+'T01:00'});N.snapshot(S.state,day);N.snapshot(S.state,D.add(day,1));C.commit(C.prepare({old:b,block:{...b,actualMinutes:100}}));A(S.state.weekSnapshots.every(s=>s.needsRecalculation));N.sync(S.state);A(S.state.weekSnapshots.every(s=>s.sourceDataRevision===2));A.equal(S.state.weekSnapshots[0].metrics.rows[1].fact,50);A.equal(S.state.weekSnapshots[1].metrics.rows[1].fact,50);});
test('Сон → дорога → работа: несовместимые резервы не удваивают круг',()=>{const week=U.monday(),base={startDateTime:week+'T10:00',endDateTime:week+'T11:00',weekId:D.weekId(week)};S.state.capacityReservations=['sleep','commute','work'].map(type=>({...base,id:type,type}));let m=N.calculate(S.state,week);A.deepEqual(m.distribution,{sleep:60});S.state.capacityReservations.shift();m=N.calculate(S.state,week);A.deepEqual(m.distribution,{commute:60});});
test('Поглощение 180 минут, пострадавшая сфера и компенсация',()=>{const old=block({protected:true,endDateTime:U.monday()+'T22:00'});C.commit(C.prepare({old,remove:true,dueToWork:true}));let m=N.calculate(S.state,U.monday());A.equal(m.lost,180);A.equal(m.absorption,100);A.equal(m.violatedCount,1);A.equal(m.affectedAreas[0],'Здоровье и тело');A(N.insights(m).some(x=>x.includes('Стоит вернуть')));const b=block({protected:true});const P=require('../app.js').ProtectionService,e=S.state.displacementLog[0];P.resolve(e.id,e.date,60,b.id);m=N.calculate(S.state,U.monday());A.equal(m.lost,120);A.equal(m.absorption,120/180*100);});
test('Экспорт содержит серию, исключение, фокус и черновик без потери',()=>{const b=block();const p=C.prepare({block:{...b,id:undefined},recurrence:{frequency:'daily',weekdays:[]}});C.commit(p);const Rec=require('../app.js').RecurrenceService,occ=Rec.blocks(S.state,U.monday(),U.monday()).find(x=>x.virtual);C.commit(C.prepare({old:occ,remove:true}));F.start({areaId:b.primaryAreaId,blockId:b.id,workMinutes:25,breakMinutes:5,longBreakMinutes:20},Date.now());F.finish(Date.now()+60000);S.state.uiState.inboxDraft={text:'Черновик',category:'thought',split:true};A.deepEqual(T.parse(JSON.stringify(S.state)),S.state);});
console.log(`${count}/${count} passed`);
