const A=require('node:assert/strict');
const {Store:S,Utils:U,FocusService:F,TaskService:T,CalendarService:C,DateUtils:D,FactService:Facts,EnergyService:E,ReservationService:R}=require('../app.js');
const tests=[],test=(n,f)=>tests.push([n,f]),minute=60000,base=+new Date('2026-09-13T23:55');
function setup(){const mem={raw:null,getItem(){return this.raw},setItem(k,v){this.raw=v}};S.init(mem);return mem;}
function task(){const t={...T.fresh(),title:'Проект'};T.save(t);return t;}
function block(t,date='2026-09-13',extra={}){const p=C.prepare({block:{title:'Блок',startDateTime:date+'T23:00',endDateTime:D.add(date,1)+'T00:00',primaryAreaId:S.state.lifeAreas[0].id,additionalAreaIds:[],taskIds:t?[t.id]:[],protected:false,status:'planned',energyRequired:'medium',note:'',actualMinutes:null,...extra}});C.commit(p);return S.state.calendarBlocks.find(b=>b.id===p.block.id);}
function start(extra={},now=base){F.start({workMinutes:50,breakMinutes:10,longBreakMinutes:20,...extra},now);}
test('Все четыре режима и пользовательский интервал',()=>{for(const[workMinutes,breakMinutes]of[[25,5],[50,10],[75,15],[30,5],[37,9]]){setup();start({workMinutes,breakMinutes});A.equal(F.timer().durationMs,workMinutes*minute);F.finish(base+workMinutes*minute);A.equal(F.timer().durationMs,breakMinutes*minute);A.equal(S.state.focusSessions[0].actualMinutes,workMinutes);}});
test('Интервалы валидируются; второй таймер запрещён',()=>{setup();for(const workMinutes of[0,-1,1.5,1441])A.throws(()=>start({workMinutes}));start();A.throws(()=>start());});
test('50 минут работы учитываются ровно один раз',()=>{setup();const t=task();start({taskId:t.id,blockId:null});A.equal(S.state.tasks[0].status,'in_progress');A.equal(F.tick(base+50*minute).length,1);A.equal(S.state.tasks[0].actualMinutes,50);A.equal(F.tick(base+90*minute).length,0);F.finish(base+90*minute);A.equal(S.state.focusSessions.length,1);A.equal(S.state.tasks[0].status,'in_progress');});
test('Пауза исключается из факта, продолжение добавляет только работу',()=>{setup();start();F.pause(base+10*minute);A.equal(F.elapsed(F.timer(),base+60*minute),10*minute);F.resume(base+60*minute);F.finish(base+75*minute);A.equal(S.state.focusSessions[0].actualMinutes,25);A.equal(S.state.focusSessions[0].segments.length,2);});
test('Работа после перезагрузки восстанавливается по timestamp',()=>{const mem=setup();start();S.init(mem);A.equal(F.elapsed(F.timer(),base+20*minute),20*minute);F.tick(base+120*minute);A.equal(S.state.focusSessions[0].actualMinutes,50);A.equal(F.timer().status,'ready');A.equal(S.state.focusSessions.length,1);});
test('Пауза сохраняется после перезагрузки',()=>{const mem=setup();start();F.pause(base+5*minute);S.init(mem);A.equal(F.timer().status,'paused');A.equal(F.elapsed(F.timer(),base+500*minute),5*minute);});
test('Досрочное завершение и остановка сохраняют полные минуты',()=>{setup();start();F.finish(base+7.9*minute,true);A.equal(S.state.focusSessions[0].actualMinutes,7);A.equal(F.timer().status,'stopped');start({},base+20*minute);F.pause(base+23*minute);F.finish(base+100*minute,true);A.equal(S.state.focusSessions[1].actualMinutes,3);});
test('Отдых не попадает в факт; следующий цикл запускается вручную',()=>{setup();start();F.finish(base+50*minute);A.equal(F.timer().phase,'break');A.equal(F.timer().status,'ready');F.next(base+50*minute);F.tick(base+60*minute);A.equal(S.state.focusSessions.length,1);A.equal(F.timer().phase,'work');A.equal(F.timer().status,'ready');F.next(base+70*minute);F.finish(base+80*minute);A.equal(S.state.focusSessions[1].actualMinutes,10);});
test('Длинный перерыв после четырёх циклов, пропуск отдыха',()=>{setup();start({workMinutes:1,breakMinutes:2,longBreakMinutes:17});for(let i=0;i<4;i++){const now=base+i*10*minute;if(i)F.next(now);F.finish(now+minute);A.equal(F.timer().durationMs,(i===3?17:2)*minute);if(i<3)F.skipBreak();}A.equal(F.timer().completedCycles,4);F.skipBreak();A.equal(F.timer().phase,'work');});
test('Без задачи и без блока не изменяет задачи и блоки',()=>{setup();task();block(null);start({blockId:null});F.finish(base+20*minute);A.equal(S.state.tasks[0].actualMinutes,null);A.equal(S.state.calendarBlocks[0].actualMinutes,null);});
test('Из блока с одной задачей задача выбирается автоматически',()=>{setup();const t=task(),b=block(t);start({blockId:b.id});F.finish(base+20*minute);A.equal(S.state.focusSessions[0].taskId,t.id);A.equal(S.state.tasks[0].actualMinutes,20);A.equal(S.state.calendarBlocks[0].actualMinutes,20);});
test('Единственный блок задачи текущего дня выбирается автоматически',()=>{setup();const t=task(),b=block(t);start({taskId:t.id});A.equal(F.timer().blockId,b.id);});
test('Несколько блоков требуют явного выбора; без блока не меняет их факт',()=>{setup();const t=task();block(t);block(t);A.throws(()=>start({taskId:t.id}));start({taskId:t.id,blockId:null});F.finish(base+20*minute);A.equal(S.state.tasks[0].actualMinutes,20);A(S.state.calendarBlocks.every(b=>b.actualMinutes===null));});
test('Из нескольких блоков факт меняет только выбранный',()=>{setup();const t=task(),a=block(t);block(t);start({taskId:t.id,blockId:a.id});F.finish(base+20*minute);A.equal(S.state.calendarBlocks.find(b=>b.id===a.id).actualMinutes,20);A.equal(S.state.calendarBlocks.find(b=>b.id!==a.id).actualMinutes,null);});
test('Ручной факт 120 заменяет 90 таймера; возврат восстанавливает 90',()=>{setup();const t=task();start({taskId:t.id,blockId:null,workMinutes:90});F.finish(base+90*minute);T.save({...S.state.tasks[0],actualMinutes:120,actualMinutesManualOverride:true});A.equal(S.state.tasks[0].actualMinutes,120);F.useTimer(t.id);A.equal(S.state.tasks[0].actualMinutes,90);A.equal(S.state.tasks[0].actualMinutesManualOverride,false);});
test('Новая сессия не перезаписывает ручной факт задачи',()=>{setup();const t=task();T.save({...t,actualMinutes:120,actualMinutesManualOverride:true});start({taskId:t.id,blockId:null});F.finish(base+30*minute);A.equal(S.state.tasks[0].actualMinutes,120);A.equal(F.taskActual(t.id),30);});
test('Возврат к таймеру без сессий оставляет null',()=>{setup();const t=task();T.save({...t,actualMinutes:0,actualMinutesManualOverride:true});F.useTimer(t.id);A.equal(S.state.tasks[0].actualMinutes,null);});
test('Граница недели: воскресенье 23:55 → понедельник 00:15 даёт 5 / 15',()=>{setup();const t=task(),b=block(t);S.state.weekSnapshots=[{weekId:'2026-W37',sourceDataRevision:1}];start({taskId:t.id,blockId:b.id});F.finish(base+20*minute);A.deepEqual(S.state.focusSessions[0].weekMinutes,{'2026-W37':5,'2026-W38':15});A.equal(S.state.tasks[0].actualMinutes,20);A.equal(S.state.weekSnapshots[0].sourceDataRevision,2);A(S.state.weekSnapshots[0].needsRecalculation);A.equal(Facts.calculate(S.state,'2026-09-13').work,5);A.equal(Facts.calculate(S.state,'2026-09-14').work,15);});
test('Пауза через границу недели не добавляет минуты ни одной неделе',()=>{setup();start();F.pause(base+2*minute);F.resume(base+15*minute);F.finish(base+18*minute);A.deepEqual(S.state.focusSessions[0].weekMinutes,{'2026-W38':3,'2026-W37':2});});
test('Таймер и подтверждённый резерв не удваивают физический факт',()=>{setup();const date=U.monday(),t=task(),b=block(t,date,{startDateTime:date+'T10:00',endDateTime:date+'T11:00'});R.ensure(S.state,date);Facts.reservation(S.state.capacityReservations.find(r=>r.type==='work'&&r.startDateTime.startsWith(date)).id,'planned_as_actual');const now=+new Date(date+'T10:00');start({taskId:t.id,blockId:b.id},now);F.finish(now+50*minute);A.equal(Facts.calculate(S.state,date).work,540);});
test('Ручной факт блока заменяет прежний вклад таймера',()=>{setup();const b=block(null);start({blockId:b.id});F.finish(base+20*minute);const current=S.state.calendarBlocks[0];C.commit(C.prepare({old:current,block:{...current,actualMinutes:10}}));A.deepEqual(S.state.calendarBlocks[0].timerCredits,{});A.equal(S.state.calendarBlocks[0].actualMinutes,10);});
test('Лимит факта блока 1440, задача получает весь интервал',()=>{setup();const t=task(),b=block(t,'2026-09-13',{actualMinutes:1430});start({taskId:t.id,blockId:b.id});F.finish(base+50*minute);A.equal(S.state.calendarBlocks[0].actualMinutes,1440);A.equal(S.state.tasks[0].actualMinutes,50);});
test('Энергия и профиль только предупреждают, не переносят',()=>{setup();const b=block(null,'2026-09-13',{energyRequired:'high'}),before=b.startDateTime;E.set('2026-09-13','low');A(E.warning(b));A.equal(b.startDateTime,before);E.set('2026-09-13','high');S.state.settings.focusPreferences={energyProfile:{evening:'low'}};A(E.warning(b));A.throws(()=>E.set('2026-09-13','bad'));});
test('Напоминание о смене положения однократно и учитывает паузу',()=>{setup();S.state.settings.focusPreferences={postureEnabled:true,postureMinutes:10};start();F.pause(base+5*minute);A.equal(F.tick(base+40*minute).length,0);F.resume(base+40*minute);A.equal(F.tick(base+45*minute).length,1);A.equal(F.tick(base+46*minute).length,0);});
test('Без активного таймера нет секундомера смены положения',()=>{setup();S.state.settings.focusPreferences={postureEnabled:true,postureMinutes:1};A.deepEqual(F.tick(base+300*minute),[]);A.equal(S.state.focusSessions.length,0);});
test('Секундное обновление не записывает хранилище каждый раз',()=>{setup();start();const writes=S.writes;for(let i=1;i<20;i++)F.tick(base+i*1000);A.equal(S.writes,writes);});
test('Копия блока не наследует фактические минуты таймера',()=>{setup();const b=block(null);start({blockId:b.id});F.finish(base+20*minute,true);const old=S.state.calendarBlocks[0],copy=C.prepare({block:{...old,actualMinutes:null}});C.commit(copy);start({blockId:copy.block.id},base+30*minute);F.finish(base+35*minute);A.equal(S.state.calendarBlocks.find(b=>b.id===copy.block.id).actualMinutes,5);});
test('Удаление задачи и блока во время сессии не оставляет активных ссылок',()=>{setup();const t=task(),b=block(t);start({taskId:t.id,blockId:b.id});T.remove(t.id);C.commit(C.prepare({old:S.state.calendarBlocks[0],remove:true}));A.equal(F.timer().taskId,null);A.equal(F.timer().blockId,null);F.finish(base+5*minute);A.equal(S.state.focusSessions[0].taskId,null);A.equal(S.state.focusSessions[0].blockId,null);});
test('Несколько блоков другого дня также требуют выбора',()=>{setup();const t=task();block(t,'2026-09-14');block(t,'2026-09-14');A.throws(()=>start({taskId:t.id}));});
test('Повреждённый таймер не затирает исходное сохранение',()=>{const mem=setup();start();const s=JSON.parse(mem.raw);s.uiState.focusTimer.durationMs=-1;mem.raw=JSON.stringify(s);const raw=mem.raw;S.init(mem);A(S.blocked);A.equal(mem.raw,raw);});
test('Реальная длительность на переходе DST считается по timestamps',()=>{const tz=process.env.TZ;try{process.env.TZ='America/New_York';setup();const from=+new Date('2026-03-08T01:30'),to=+new Date('2026-03-08T03:30');start({workMinutes:120},from);F.finish(to);A.equal(S.state.focusSessions[0].actualMinutes,60);A.equal(Object.values(S.state.focusSessions[0].weekMinutes).reduce((n,v)=>n+v,0),60);}finally{if(tz===undefined)delete process.env.TZ;else process.env.TZ=tz;}});
test('Фокус для сферы без задачи сохраняет сферу после reload и в сессии',()=>{const mem=setup(),areaId=S.state.lifeAreas[9].id;start({areaId,blockId:null});S.init(mem);A.equal(F.timer().areaId,areaId);F.finish(base+10*minute);A.equal(S.state.focusSessions[0].areaId,areaId);A.equal(S.state.focusSessions[0].taskId,null);A.equal(S.state.calendarBlocks.length,0);});
test('При запуске из задачи подставляется её сфера',()=>{setup();const t=task();start({taskId:t.id,areaId:S.state.lifeAreas[9].id,blockId:null});A.equal(F.timer().areaId,t.areaId);});
let failed=0;for(const[n,f]of tests)try{f();console.log('OK '+n)}catch(e){failed++;console.error('FAIL '+n+'\n'+e.stack)}console.log(`${tests.length-failed}/${tests.length} passed`);process.exitCode=failed?1:0;
